### PR TITLE
Updates to `import_local()` and `swmpr()`

### PR DESCRIPTION
**Pull request by padilla410**
This pull request adds two small updates to `import_local()` and `swmpr()`.

`swmpr()`
I suggest swapping `trimws()` for `gsub()` when removing trailing white spaces from the QAQC columns. I ran into formatting issues when manually converting data into swmpr objects when the QAQC columns did not have trialing white space. Using `trimws()` corrects this issue.

`import_local()`
I added a new argument to `import_local` called `collMethd`. This argument allows the user to filter nutrient data if they want, since CDMO provides both monthly sampling data and diel sampling data together.

Please let me know if there are any issues with this pull request! This is my first time contributing to someone else's package.

### CODE REVIEW

**Comment by padilla410** [comment]
Ah, ok a bit more experimenting, and the swmpr update is unnecessary. The issue was mine (going between tidyverse data.frames and converting to SWMPr)

**Comment by fawda123** [comment]
Hi Julie, thanks for the PR.  I'll just merge as is, the switch to `trimws` seems harmless enough.

**Comment by fawda123** [comment]
Also, I updated the .Rd file for `import_local()` for the new argument and I noticed that the actual argument was not included in the function call.  I added the default value as `collMethd = c("1", "2")`.  Can you verify that this works as intended? 

a2b977159378e4b50717a10a61860724a3ec75ce

**Comment by fawda123** [comment]
Works with some data from sfbccnut.
```
tmp1 <- import_local('C:/Users/Marcus.SCCWRP2K/Desktop/507840.zip', station_code = 'sfbccnut', collMethd = '1')
dim(tmp1)
# [1] 297  13
head(tmp1)
# datetimestamp  po4f f_po4f  nh4f f_nh4f  no2f f_no2f  no3f f_no3f no23f f_no23f chla_n f_chla_n
# 1 2006-01-19 13:30:00 0.077    <4> 0.098 <4>  H 0.016 <4>  H 0.401 <4>  C 0.417  <4>  H     NA   <4>  M
# 2 2006-01-19 13:31:00 0.077    <4> 0.106 <4>  H 0.016 <4>  H 0.407 <4>  C 0.423  <4>  H     NA   <4>  M
# 3 2006-02-15 16:15:00 0.058    <4> 0.061 <4>  H 0.006 <4>  H 0.284 <4>  C 0.290  <4>  H    3.4      <4>
#   4 2006-02-15 16:16:00 0.058    <4> 0.067 <4>  H 0.006 <4>  H 0.285 <4>  C 0.291  <4>  H    0.1   <4>  S
# 5 2006-03-09 12:29:00 0.060    <4> 0.074 <4>  H 0.007 <4>  H 0.287 <4>  C 0.294  <4>  H   10.3      <4>
#   6 2006-03-09 12:30:00 0.061    <4> 0.063 <4>  H 0.007 <4>  H 0.287 <4>  C 0.294  <4>  H   11.1      <4>
tmp2 <- import_local('C:/Users/Marcus.SCCWRP2K/Desktop/507840.zip', station_code = 'sfbccnut', collMethd = '2')
dim(tmp2)
# [1] 2506   13
head(tmp2)
# datetimestamp  po4f     f_po4f  nh4f f_nh4f  no2f f_no2f  no3f     f_no3f no23f f_no23f chla_n f_chla_n
# 1 2006-04-18 10:30:00 0.086        <4> 0.049 <4>  H 7e-03 <4>  H 0.211     <4>  C 0.218     <4>   13.4      <4>
#   2 2006-04-18 13:00:00 0.067        <4> 0.055 <4>  H 8e-03 <4>  H 0.236     <4>  C 0.244     <4>   14.0      <4>
#   3 2006-04-18 15:29:00 0.088        <4> 0.059 <4>  H 1e-04 <4>  B    NA <4>  C - B 0.218     <4>    1.6      <4>
#   4 2006-04-18 18:00:00 0.098 <4>  S - K 0.067 <4>  H 1e-04 <4>  B    NA <4>  C - B 0.226     <4>    1.8      <4>
#   5 2006-04-18 20:30:00 0.068        <4> 0.047 <4>  H 7e-03 <4>  H 0.231     <4>  C 0.238     <4>    9.2      <4>
#   6 2006-04-18 22:59:00 0.068 <4>  S - K 0.049 <4>  H 6e-03 <4>  H 0.221     <4>  C 0.227     <4>    7.8      <4>
tmp3 <- import_local('C:/Users/Marcus.SCCWRP2K/Desktop/507840.zip', station_code = 'sfbccnut', collMethd = c('1', '2'))
dim(tmp3)
# [1] 2803   13
head(tmp3)
# datetimestamp  po4f f_po4f  nh4f f_nh4f  no2f f_no2f  no3f f_no3f no23f f_no23f chla_n f_chla_n
# 1 2006-01-19 13:30:00 0.077    <4> 0.098 <4>  H 0.016 <4>  H 0.401 <4>  C 0.417  <4>  H     NA   <4>  M
# 2 2006-01-19 13:31:00 0.077    <4> 0.106 <4>  H 0.016 <4>  H 0.407 <4>  C 0.423  <4>  H     NA   <4>  M
# 3 2006-02-15 16:15:00 0.058    <4> 0.061 <4>  H 0.006 <4>  H 0.284 <4>  C 0.290  <4>  H    3.4      <4>
#   4 2006-02-15 16:16:00 0.058    <4> 0.067 <4>  H 0.006 <4>  H 0.285 <4>  C 0.291  <4>  H    0.1   <4>  S
# 5 2006-03-09 12:29:00 0.060    <4> 0.074 <4>  H 0.007 <4>  H 0.287 <4>  C 0.294  <4>  H   10.3      <4>
#   6 2006-03-09 12:30:00 0.061    <4> 0.063 <4>  H 0.007 <4>  H 0.287 <4>  C 0.294  <4>  H   11.1      <4>
```

**Pull request merged**
